name: Test if the example app still builds on Linux x64
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "common/**"
      - "example/**"
      - "lib/**"
      - "linux/**"
      - "third/**"
      - "pubspec.yaml"
      - ".github/workflows/test_linux_x64.yaml"
  pull_request:
    paths:
      - "common/**"
      - "example/**"
      - "lib/**"
      - "linux/**"
      - "third/**"
      - "pubspec.yaml"
      - ".github/workflows/test_linux_x64.yaml"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libgtkmm-3.0-dev libgtkmm-3.0-1t64 clang cmake pkg-config build-essential
      - run: flutter --version
      - run: lsb_release -a
      - run: clang --version
      - run: cmake --version
      - run: g++ --version
      - run: (cd example && flutter build linux)
